# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'Rxzhihu' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

    # Rx
  pod 'RxSwift', '~> 3.0'
  pod 'RxCocoa', '~> 3.0'
  pod 'RxDataSources', '~> 1.0'

  # UI
  pod 'SnapKit', '~> 3.0'
  pod 'Kingfisher', '>= 3.0'
  pod 'MJRefresh'
  #pod 'PullToRefreshKit', '~> 0.4'  #https://github.com/LeoMobileDeveloper/PullToRefreshKit
    pod 'Toaster', '~> 2.0' #https://github.com/devxoul/Toaster
    pod 'SVProgressHUD' #https://github.com/SVProgressHUD/SVProgressHUD

  pod 'Alamofire', '~> 4.0' 
  pod 'AlamofireObjectMapper'

  pod 'XCGLogger', '~> 4.0.0'

  # Misc.
  pod 'Then', '~> 2.1'
  pod 'ReusableKit', '~> 1.1'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end
